package com.example.Arturo.model;

/**
 * Response DTO for the {@code GET /search} endpoint.
 *
 * <p>Contains the best-matching document's ID, its cosine similarity score,
 * and a natural language answer generated by the LLM using the matched chunk as context.</p>
 */
public class SearchResult {

    private final String docId;
    private final double score;
    private final String answer;

    /**
     * Constructs a search result.
     *
     * @param docId  identifier of the matched document (derived from filename)
     * @param score  cosine similarity score (0.0 to 1.0)
     * @param answer LLM-generated answer based on the best-matching chunk,
     *               or raw chunk content as fallback if LLM is unavailable
     */
    public SearchResult(String docId, double score, String answer) {
        this.docId = docId;
        this.score = score;
        this.answer = answer;
    }

    public String getDocId() {
        return docId;
    }

    public double getScore() {
        return score;
    }

    public String getAnswer() {
        return answer;
    }
}
